# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ai_service_pb2 as ai__service__pb2


class AIGradingServiceStub(object):
    """AI批改服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeText = channel.unary_unary(
                '/ai_service.AIGradingService/RecognizeText',
                request_serializer=ai__service__pb2.ImageRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TextResponse.FromString,
                )
        self.GradeSubjective = channel.unary_unary(
                '/ai_service.AIGradingService/GradeSubjective',
                request_serializer=ai__service__pb2.SubjectiveRequest.SerializeToString,
                response_deserializer=ai__service__pb2.GradingResponse.FromString,
                )
        self.AnswerQuestion = channel.unary_unary(
                '/ai_service.AIGradingService/AnswerQuestion',
                request_serializer=ai__service__pb2.QuestionRequest.SerializeToString,
                response_deserializer=ai__service__pb2.AnswerResponse.FromString,
                )
        self.RecommendExercises = channel.unary_unary(
                '/ai_service.AIGradingService/RecommendExercises',
                request_serializer=ai__service__pb2.RecommendRequest.SerializeToString,
                response_deserializer=ai__service__pb2.RecommendResponse.FromString,
                )
        self.ProcessRecommendationFeedback = channel.unary_unary(
                '/ai_service.AIGradingService/ProcessRecommendationFeedback',
                request_serializer=ai__service__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=ai__service__pb2.FeedbackResponse.FromString,
                )
        self.AnalyzeLearningStatus = channel.unary_unary(
                '/ai_service.AIGradingService/AnalyzeLearningStatus',
                request_serializer=ai__service__pb2.LearningAnalysisRequest.SerializeToString,
                response_deserializer=ai__service__pb2.LearningAnalysisResponse.FromString,
                )
        self.AssessSpeech = channel.unary_unary(
                '/ai_service.AIGradingService/AssessSpeech',
                request_serializer=ai__service__pb2.SpeechAssessmentRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SpeechAssessmentResponse.FromString,
                )
        self.OptimizePushContent = channel.unary_unary(
                '/ai_service.AIGradingService/OptimizePushContent',
                request_serializer=ai__service__pb2.OptimizePushContentRequest.SerializeToString,
                response_deserializer=ai__service__pb2.OptimizePushContentResponse.FromString,
                )


class AIGradingServiceServicer(object):
    """AI批改服务
    """

    def RecognizeText(self, request, context):
        """OCR识别
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GradeSubjective(self, request, context):
        """主观题评分
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnswerQuestion(self, request, context):
        """AI答疑
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecommendExercises(self, request, context):
        """个性化推荐
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessRecommendationFeedback(self, request, context):
        """推荐反馈（新增）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeLearningStatus(self, request, context):
        """学情分析（新增）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssessSpeech(self, request, context):
        """口语评测（新增）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimizePushContent(self, request, context):
        """推送文案优化（新增）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIGradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeText': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeText,
                    request_deserializer=ai__service__pb2.ImageRequest.FromString,
                    response_serializer=ai__service__pb2.TextResponse.SerializeToString,
            ),
            'GradeSubjective': grpc.unary_unary_rpc_method_handler(
                    servicer.GradeSubjective,
                    request_deserializer=ai__service__pb2.SubjectiveRequest.FromString,
                    response_serializer=ai__service__pb2.GradingResponse.SerializeToString,
            ),
            'AnswerQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AnswerQuestion,
                    request_deserializer=ai__service__pb2.QuestionRequest.FromString,
                    response_serializer=ai__service__pb2.AnswerResponse.SerializeToString,
            ),
            'RecommendExercises': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendExercises,
                    request_deserializer=ai__service__pb2.RecommendRequest.FromString,
                    response_serializer=ai__service__pb2.RecommendResponse.SerializeToString,
            ),
            'ProcessRecommendationFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessRecommendationFeedback,
                    request_deserializer=ai__service__pb2.FeedbackRequest.FromString,
                    response_serializer=ai__service__pb2.FeedbackResponse.SerializeToString,
            ),
            'AnalyzeLearningStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeLearningStatus,
                    request_deserializer=ai__service__pb2.LearningAnalysisRequest.FromString,
                    response_serializer=ai__service__pb2.LearningAnalysisResponse.SerializeToString,
            ),
            'AssessSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.AssessSpeech,
                    request_deserializer=ai__service__pb2.SpeechAssessmentRequest.FromString,
                    response_serializer=ai__service__pb2.SpeechAssessmentResponse.SerializeToString,
            ),
            'OptimizePushContent': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizePushContent,
                    request_deserializer=ai__service__pb2.OptimizePushContentRequest.FromString,
                    response_serializer=ai__service__pb2.OptimizePushContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_service.AIGradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIGradingService(object):
    """AI批改服务
    """

    @staticmethod
    def RecognizeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_service.AIGradingService/RecognizeText',
            ai__service__pb2.ImageRequest.SerializeToString,
            ai__service__pb2.TextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GradeSubjective(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_service.AIGradingService/GradeSubjective',
            ai__service__pb2.SubjectiveRequest.SerializeToString,
            ai__service__pb2.GradingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnswerQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_service.AIGradingService/AnswerQuestion',
            ai__service__pb2.QuestionRequest.SerializeToString,
            ai__service__pb2.AnswerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecommendExercises(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_service.AIGradingService/RecommendExercises',
            ai__service__pb2.RecommendRequest.SerializeToString,
            ai__service__pb2.RecommendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessRecommendationFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_service.AIGradingService/ProcessRecommendationFeedback',
            ai__service__pb2.FeedbackRequest.SerializeToString,
            ai__service__pb2.FeedbackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnalyzeLearningStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_service.AIGradingService/AnalyzeLearningStatus',
            ai__service__pb2.LearningAnalysisRequest.SerializeToString,
            ai__service__pb2.LearningAnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AssessSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_service.AIGradingService/AssessSpeech',
            ai__service__pb2.SpeechAssessmentRequest.SerializeToString,
            ai__service__pb2.SpeechAssessmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OptimizePushContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_service.AIGradingService/OptimizePushContent',
            ai__service__pb2.OptimizePushContentRequest.SerializeToString,
            ai__service__pb2.OptimizePushContentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
